### ISSUE TITLE
Сломанные hyperref в содержании

### ISSUE THREAD

**Issue by dmitriyselivanov** [itonik/spbu_diploma#1]
Если кликнуть на введение/постановку задачи в содержании, то переходит на титульный лист, то же самое с выводами / списком литературы. Фиксится с помощью добавления \phantomsection перед этими главами.

P.S. мне лень делать пулл реквест :)

**Comment by dmitriyselivanov** [comment]
Спасибо за шаблон, бай зэ вей

**Comment by itonik** [comment]
Спасибо за фидбэк. Если вдруг сделаешь что-нибудь для "Приложения", открывай новый issue или pr, я пока не делал ничего для той главы.
