### ISSUE TITLE
Размер шрифтов не компилятся

### ISSUE THREAD

**Issue by anatolyefimov** [itonik/spbu_diploma#2]
Вроооде как, для \section и \subsection не компилятся 16pt  и 18pt не компилятся, вроде как им присваивается одинаковый размер 17.28 pt. И я даже нагуглить не смог, как пофиксить.

**Comment by itonik** [comment]
Это косяк шрифта, насколько я помню. В прошлом году я не смог придумать, как это обойти (на самом деле никто не узнает, только т-сс :) )

Решение может быть достигнуто только если получится найти другой шрифт, который выглядит так же, но может нормально скейлиться. Другого способа я не знаю.

**Comment by itonik** [comment]
Будет круто если кто-то посоветует шрифт тут, в ближайшие дни я не смогу заняться этой проблемой

**Comment by anatolyefimov** [comment]
В тех лайв оказывается любой другой стнадартный шрифт скейлится, но ни один из не не похож на Computer Modern.

**Comment by itonik** [comment]
Tempora-TLF выглядит лучшим решением - что-то между CM и Times. Правда, менять придётся не только заголовки - потому что иначе выглядит уродски.
Я думаю, в ближайшее время сделаю отдельную ветку именно с Tempora-TLF, там подровняем и, может быть, даже сделаем дефолтной опцией

**Comment by itonik** [comment]
Ну кажется можно закрывать. Косяков не появилось новых? Я вроде как не заметил
